### ISSUE TITLE
I2C master-slave switch

### ISSUE THREAD

**Issue by Yu-jinyan** [enndubyu/ipmb_device#4]
I noticed that in your example program useage.c, you did not switch between master and slave modes for i2c, and just performed read and write operations. As far as I know, IPMB is master-write, so shouldn’t you write (request) as a master and receive the response as a slave?

**Comment by enndubyu** [comment]
Sorry I didn't see this earlier. 

Yes, IPMB is master write. In order to use this driver, the i2c peripheral needs to support acting as a master and slave on the same bus, sometimes referred to as multi-master mode. 

`ipmb_write()` calls `i2c_transfer()` which will do a master write even when slave mode is enabled. When the other device sends the response, the slave callback will store the message in a queue to make it available for `ipmb_read()`.
